import Link from "next/link";
import { Sparkles, ScanFace, FlaskConical, TrendingUp, History } from "lucide-react";

const STEPS = [
  {
    icon: ScanFace,
    title: "Position your face",
    body: "Center your face in the frame. Make sure there is good lighting, no hat, and no glasses — the camera needs a clear view of your skin.",
  },
  {
    icon: FlaskConical,
    title: "AI skin diagnosis",
    body: "OurSkinOurFuture analyzes multiple concern areas — acne, redness, texture, pores, dark circles, firmness, and more — with confidence scores and zone mapping.",
  },
  {
    icon: TrendingUp,
    title: "See your projection",
    body: "Watch a realistic treatment simulation blend your current photo with a projected improved state over time, so you can see what consistent care could achieve.",
  },
  {
    icon: History,
    title: "Track clinical progress",
    body: "Save scans and compare them week over week. Every new scan measures exactly how your skin is responding — no guesswork, just data.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-paper">
      <header className="max-w-3xl mx-auto px-5 pt-8 pb-2 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-3">
          <img src="/Logo.png" alt="OurSkinOurFuture" className="w-10 h-10 rounded-2xl object-cover shrink-0 border border-border" />
          <span className="text-base font-semibold tracking-tight text-ink">
            Our<span className="text-gold">Skin</span>Our<span className="text-gold">Future</span>
          </span>
        </Link>
        <Link
          href="/dashboard"
          className="text-xs font-medium px-4 py-2 rounded-2xl bg-ink text-paper"
        >
          Launch Demo
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-5">
        {/* Hero */}
        <section className="pt-14 pb-10 text-center">
          <h1 className="text-4xl sm:text-5xl font-bold leading-[1.1] mb-5 text-ink">
            Predictive clinical skin intelligence.
            <br />
            Not another filter.
          </h1>
          <p className="text-base leading-relaxed max-w-xl mx-auto mb-8 text-muted">
            OurSkinOurFuture turns a single selfie into a dermatologist-grade diagnostic session:
            multi-concern analysis, treatment simulation, and an evidence-based care plan — all on your phone.
          </p>
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 rounded-2xl px-7 py-4 text-sm font-semibold bg-ink text-paper active:scale-[0.98] transition-transform"
          >
            Start Analysis
          </Link>
          <p className="text-[11px] mt-3 text-faint">No account required to try · Sign in later to save progress</p>
        </section>

        {/* How it works */}
        <section className="py-10">
          <div className="text-xs font-mono uppercase tracking-widest mb-6 text-center text-muted">
            Clinical Pipeline
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {STEPS.map((step, i) => {
              const Icon = step.icon;
              return (
                <div key={step.title} className="rounded-3xl p-5 bg-card border border-border">
                  <div className="flex items-center gap-2.5 mb-3">
                    <div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 bg-[#F0EBDD]">
                      <Icon size={15} className="text-[#8A7A52]" />
                    </div>
                    <span className="text-[10px] font-mono text-faint">STEP {i + 1}</span>
                  </div>
                  <h3 className="text-sm font-semibold mb-1.5 text-ink">{step.title}</h3>
                  <p className="text-xs leading-relaxed text-muted">{step.body}</p>
                </div>
              );
            })}
          </div>
        </section>

        {/* Trust */}
        <section className="py-10 pb-16">
          <div className="rounded-3xl p-6 bg-ink">
            <div className="flex items-center gap-2 mb-2.5">
              <Sparkles size={13} className="text-gold" />
              <span className="text-[11px] font-mono uppercase tracking-widest text-gold">Powered By</span>
            </div>
            <p className="text-sm leading-relaxed text-[#F0EBDD]">
              Skin analysis and simulation run on YouCam Skin AI. Recommendations are generated by
              Qwen using your exact scan metrics — not a template, but a targeted regimen built from
              your real diagnostic data.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
